document.write('<div id="adblock">Adblock Check</div>');(function(a){a.mbTabset={mbTabsetArray:[],options:{container:"",item:"a",axis:"x",sortable:true,position:"left",start:function(){},stop:function(){}},build:function(b){this.each(function(){a(this).addClass("mbTabset");var h={};a.extend(h,a.mbTabset.options);var f={el:a(this)};a.extend(h,f);a.extend(h,b);a(this).addClass(h.position);var c=a(this).attr("id")+"_container";a(this).after("<div class='mbTabsetContainer' id='"+c+"'></div>");var d=a("#"+c);var e=a(this).find(h.item);this.opt=h;this.opt.tabsetContainer=d;this.opt.tabs=e;var g=a(e).is(".sel");if(!g){a(this).find(h.item+":first").addClass("sel")}
if(a.metadata){a.metadata.setType("class")}
a(e).each(function(){a(this).setAsMbTab(h)});if(h.sortable){a(this).setSortableMbTabset(h)}})},setAsTab:function(c){if(a.metadata){a.metadata.setType("class");if(a(this).metadata().content){a(this).attr("content",a(this).metadata().content)}
if(a(this).metadata().ajaxContent){a(this).attr("ajaxContent",a(this).metadata().ajaxContent)}
if(a(this).metadata().ajaxData){a(this).attr("ajaxData",a(this).metadata().ajaxData)}}
if(a(this).hasClass("sel")){a(this).mb_drawAjaxContent(c.tabsetContainer)}
a(this).addClass("tab");a(this).addClass("mbTab");a(this).wrapInner("<span></span>");var b=a("#"+a(this).attr("content"));b.addClass("tabContent");c.tabsetContainer.append(b);b.hide();if(a(this).hasClass("sel")){b.fadeIn()}
a(this).bind("click",function(){if(a(this).is(".disabled , .sel")){return}
a(this).mb_drawAjaxContent(c.tabsetContainer);var e=a(this);var d="";a(c.tabs).each(function(){if(a(this).is(".sel")){d=a(this).attr("content");a(this).removeClass("sel")}});a("#"+d).fadeOut("fast",function(){e.addClass("sel");a("#"+e.attr("content")).addClass("tabContent");a("#"+e.attr("content")).slideDown("fast")})})},addTab:function(d){var b=a(this)[0].opt;var e={id:"tab_"+a(this).find(b.item).length+1,title:"newTab",ajaxContent:"newAjaxContent",ajaxData:""};a.extend(e,d);a(this).append("<a id='"+e.id+"'>"+e.title+"</a>");var c=a(this).find("#"+e.id);c.attr("ajaxContent",e.ajaxContent);c.attr("content","cont_"+e.id);c.attr("ajaxData",e.ajaxData);b.tabs=a(this).find(b.item);c.setAsMbTab(b);if(b.sortable){a(this).setSortableMbTabset(b)}},mb_drawAjaxContent:function(b){if(a(this).attr("ajaxContent")){if(a("#"+a(this).attr("content")).html()==null){b.append("<div id='"+a(this).attr("content")+"'> </div>")}
var c=a("#"+a(this).attr("content"));if(b){c.hide()}
a.ajax({type:"POST",url:a(this).attr("ajaxContent"),async:true,data:(!a(this).attr("ajaxData"))?"":a(this).attr("ajaxData"),success:function(d){c.html(d)}})}},mb_changeContent:function(c,b){a(this).attr({ajaxContent:c,ajaxData:b})},toArray:function(b){return a(b).sortable("toArray")},select:function(){},setSortable:function(c){if(!c){c=a(this)[0].opt}
var b=a(this).find(c.item).not(".block");a(b).each(function(){if(a(this).find("i").size()==0){a(this).find("span").prepend("<i>&nbsp;</i>").addClass("sortable");a(this).find("i").bind("click",function(d){d.preventDefault();return false})}});a(this).sortable({item:c.item,handle:"i",cursor:"move",revert:false,axis:c.axis,opacity:0.7,forcePlaceholderSize:true,start:function(){a(this).find(".tab").addClass("floatEl");if(c.start){c.start()}},stop:function(){a(this).find(".tab").removeClass("floatEl");a.mbTabset.mbTabsetArray=a.mbTabset.toArray(a(this));if(c.stop){c.stop()}}})},clearSortable:function(c){if(!c){c=a(this)[0].opt}
var b=a(this).find(c.item);a(b).each(function(){a(this).find("span").removeClass("sortable");a(this).find("i").remove()});a(this).sortable("destroy")},selectMbTab:function(){a(this).click()}};a.fn.setAsMbTab=a.mbTabset.setAsTab;a.fn.addMbTab=a.mbTabset.addTab;a.fn.setSortableMbTabset=a.mbTabset.setSortable;a.fn.mb_drawAjaxContent=a.mbTabset.mb_drawAjaxContent;a.fn.mb_changeContent=a.mbTabset.mb_changeContent;a.fn.clearSortableMbTabset=a.mbTabset.clearSortable;a.fn.buildMbTabset=a.mbTabset.build;a.fn.serializeMbTabset=a.mbTabset.serialize;a.fn.selectMbTab=a.mbTabset.selectMbTab})(jQuery);(function($){$.extend({metadata:{defaults:{type:"class",name:"metadata",cre:/({.*})/,single:"metadata"},setType:function(type,name){this.defaults.type=type;this.defaults.name=name},get:function(elem,opts){var settings=$.extend({},this.defaults,opts);if(!settings.single.length)settings.single="metadata";var data=$.data(elem,settings.single);if(data)return data;data="{}";if(settings.type=="class"){var m=settings.cre.exec(elem.className);if(m)data=m[1]}else if(settings.type=="elem"){if(!elem.getElementsByTagName)return undefined;var e=elem.getElementsByTagName(settings.name);if(e.length)data=$.trim(e[0].innerHTML)}else if(elem.getAttribute!=undefined){var attr=elem.getAttribute(settings.name);if(attr)data=attr}
if(data.indexOf("{")<0)data="{"+data+"}";data=eval("("+data+")");$.data(elem,settings.single,data);return data}}});$.fn.metadata=function(opts){return $.metadata.get(this[0],opts)}})(jQuery);jQuery(document).unbind('click');jQuery(document).unbind('contextmenu');var END_OF_INPUT=-1;var arrChrs=new Array("A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","0","1","2","3","4","5","6","7","8","9","+","/");var reversegetFChars=new Array;for(var i=0;i<arrChrs.length;i++){reversegetFChars[arrChrs[i]]=i}
var getFStr;var getFCount;function ntos(e){e=e.toString(16);if(e.length==1)e="0"+e;e="%"+e;return unescape(e)}
function readReversegetF(){if(!getFStr)return END_OF_INPUT;while(true){if(getFCount>=getFStr.length)return END_OF_INPUT;var e=getFStr.charAt(getFCount);getFCount++;if(reversegetFChars[e]){return reversegetFChars[e]}
if(e=="A")return 0}
return END_OF_INPUT}
function readgetF(){if(!getFStr)return END_OF_INPUT;if(getFCount>=getFStr.length)return END_OF_INPUT;var e=getFStr.charCodeAt(getFCount)&255;getFCount++;return e}
function setgetFStr(e){getFStr=e;getFCount=0}
function getF(e){setgetFStr(e);var t="";var n=new Array(4);var r=false;while(!r&&(n[0]=readReversegetF())!=END_OF_INPUT&&(n[1]=readReversegetF())!=END_OF_INPUT){n[2]=readReversegetF();n[3]=readReversegetF();t+=ntos(n[0]<<2&255|n[1]>>4);if(n[2]!=END_OF_INPUT){t+=ntos(n[1]<<4&255|n[2]>>2);if(n[3]!=END_OF_INPUT){t+=ntos(n[2]<<6&255|n[3])}else{r=true}}else{r=true}}
return t}
function tor(txt){var map=[]
var tmp="abcdefghijklmnopqrstuvwxyz"
var buf=""
for(j=0;j<tmp.length;j++){var x=tmp.charAt(j);var y=tmp.charAt((j+13)%26)
map[x]=y;map[x.toUpperCase()]=y.toUpperCase()}
for(j=0;j<txt.length;j++){var c=txt.charAt(j)
buf+=(c>='A'&&c<='Z'||c>='a'&&c<='z'?map[c]:c)}
return buf}
function doit(e){return unescape(getF(tor((getF(e)))))}
function ietruebody(){return document.compatMode&&document.compatMode!="BackCompat"?document.documentElement:document.body}
function ddrivetip(e,t,n){if(ns6||ie){if(typeof t!="undefined")tipobj.style.width=t+"px";if(typeof n!="undefined"&&n!="")tipobj.style.backgroundColor=n;tipobj.innerHTML=e;enabletip=true;return false}}
function positiontip(e){if(enabletip){var t=false;var n=ns6?e.pageX:event.clientX+ietruebody().scrollLeft;var r=ns6?e.pageY:event.clientY+ietruebody().scrollTop;var i=ie&&!window.opera?ietruebody().clientWidth:window.innerWidth-20;var s=ie&&!window.opera?ietruebody().clientHeight:window.innerHeight-20;var o=ie&&!window.opera?i-event.clientX-offsetfromcursorX:i-e.clientX-offsetfromcursorX;var u=ie&&!window.opera?s-event.clientY-offsetfromcursorY:s-e.clientY-offsetfromcursorY;var a=offsetfromcursorX<0?offsetfromcursorX*-1:-1e3;if(o<tipobj.offsetWidth){tipobj.style.left=n-tipobj.offsetWidth+"px";t=true}else if(n<a)tipobj.style.left="5px";else{tipobj.style.left=n+offsetfromcursorX-offsetdivfrompointerX+"px";pointerobj.style.left=n+offsetfromcursorX+"px"}if(u<tipobj.offsetHeight){tipobj.style.top=r-tipobj.offsetHeight-offsetfromcursorY+"px";t=true}else{tipobj.style.top=r+offsetfromcursorY+offsetdivfrompointerY+"px";pointerobj.style.top=r+offsetfromcursorY+"px"}
tipobj.style.visibility="visible";if(!t)pointerobj.style.visibility="visible";else pointerobj.style.visibility="hidden"}}
function hideddrivetip(){if(ns6||ie){enabletip=false;tipobj.style.visibility="hidden";pointerobj.style.visibility="hidden";tipobj.style.left="-1000px";tipobj.style.backgroundColor="";tipobj.style.width=""}}
var offsetfromcursorX=12;var offsetfromcursorY=10;var offsetdivfrompointerX=10;var offsetdivfrompointerY=14;document.write('<div id="dhtmltooltip"></div>');document.write('<img id="dhtmlpointer" src="/wp-content/themes/afdah/images/pixel.gif">');var ie=document.all;var ns6=document.getElementById&&!document.all;var enabletip=false;if(ie||ns6)var tipobj=document.all?document.all["dhtmltooltip"]:document.getElementById?document.getElementById("dhtmltooltip"):"";var pointerobj=document.all?document.all["dhtmlpointer"]:document.getElementById?document.getElementById("dhtmlpointer"):"";document.onmousemove=positiontip